package main

import (
	"bytes"
	"fmt"
	"io/fs"
	"os"
	"os/exec"
	"path"
	"path/filepath"
	"sort"
	"strings"

	"golang.org/x/mod/modfile"
	"golang.org/x/mod/module"
)

// gomodResult describes a generated (or, in dry mode, planned) target go.mod.
type gomodResult struct {
	dir         string   // module dir relative to the tree root ("." = root)
	module      string   // target module path
	pins        []string // "path version" (or "path @latest (unresolved)")
	addReplace  int
	dropReplace int
	unresolved  bool   // an @latest could not be resolved (dry only)
	content     []byte // generated bytes (nil when unresolved in dry)
	diff        string // dry only: new|identical|differs|unresolved (@latest)
}

// generateStep regenerates target go.mod files from source whenever an importmap
// is present. Real runs write the file; dry runs only build the plan. It also
// settles the root "version" bookkeeping: consumed by some module → required;
// declared but consumed by none → dead conf field, loud error.
//
// Per-module `go mod tidy` (which regenerates go.sum) runs ONLY when the run's
// buildtest question is "module": tidy is module-alone by Go's own design
// (workspace-blind), so it is honest only once the modules it resolves are
// published. A "workspace" run is the pre-publish world — family pins may name
// tags that don't exist yet — and must not tidy; the go.mods land as generated
// and the module-alone pass completes go.sum after the pins publish.
func generateStep(cfg Config, keeps patternSet, tm treeMap, srcModDirs []string, res *result, dry bool) {
	if cfg.ImportMap == nil {
		return
	}
	anyConsumed := false
	for _, relDir := range srcModDirs {
		trelDir, ok := tm.srcToTarget(relDir)
		if !ok {
			continue // outside the clone domain (excluded/unmapped territory never reaches here)
		}
		modRel := path.Join(trelDir, "go.mod")
		if isKeptPath(keeps, modRel) {
			continue // kept: left as-is, copy already skipped it
		}
		srcPath := filepath.Join(cfg.From, filepath.FromSlash(relDir), "go.mod")
		gr, consumed := genGoMod(srcPath, cfg.ImportMap, cfg.Version, dry)
		gr.dir = trelDir
		anyConsumed = anyConsumed || consumed

		if dry {
			gr.diff = planDiff(filepath.Join(cfg.To, filepath.FromSlash(trelDir), "go.mod"), gr)
			res.gomods = append(res.gomods, gr)
			continue
		}

		modDir := filepath.Join(cfg.To, filepath.FromSlash(trelDir))
		if err := os.MkdirAll(modDir, 0o755); err != nil {
			die(4, "mkdir %s: %v\n", trelDir, err)
		}
		if err := os.WriteFile(filepath.Join(modDir, "go.mod"), gr.content, 0o644); err != nil {
			die(4, "write go.mod %s: %v\n", trelDir, err)
		}
		if cfg.Verbose {
			stderr("  gomod %s\n", modRel)
		}
		if cfg.BuildTest == "module" {
			tidyModule(modDir)
		}
		res.gomods = append(res.gomods, gr)
	}
	if cfg.Version != "" && !anyConsumed {
		die(1, "conf: version %q declared but no generated go.mod consumes a mapped module (drop the key)\n", cfg.Version)
	}
}

func planDiff(targetPath string, gr gomodResult) string {
	if gr.unresolved {
		return "unresolved (@latest)"
	}
	existing, err := os.ReadFile(targetPath)
	if err != nil {
		return "new"
	}
	if bytes.Equal(existing, gr.content) {
		return "identical"
	}
	return "differs"
}

// discoverSourceModules returns source-relative dirs containing a go.mod,
// skipping source-skipped subtrees.
func discoverSourceModules(from string, skips patternSet) []string {
	var dirs []string
	_ = filepath.WalkDir(from, func(p string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if !d.IsDir() {
			return nil
		}
		rel := relOf(from, p)
		if rel != "." && skips.protects(rel) {
			return fs.SkipDir
		}
		if fileExists(filepath.Join(p, "go.mod")) {
			dirs = append(dirs, rel)
		}
		return nil
	})
	sort.Strings(dirs)
	return dirs
}

// genGoMod builds the target go.mod from the source one per the importmap
// rules. The returned bool reports whether the root-level version was consumed
// (some require hit a mapped module).
func genGoMod(srcPath string, im map[string]importEntry, rootVersion string, dry bool) (gomodResult, bool) {
	data, err := os.ReadFile(srcPath)
	if err != nil {
		die(4, "read %s: %v\n", srcPath, err)
	}
	f, err := modfile.Parse(srcPath, data, nil)
	if err != nil {
		die(4, "parse %s: %v\n", srcPath, err)
	}

	var gr gomodResult
	consumed := false

	// module line: mapped -> "to", else copied
	if f.Module != nil {
		if e, ok := im[f.Module.Mod.Path]; ok {
			if err := f.AddModuleStmt(e.To); err != nil {
				die(4, "set module %s: %v\n", e.To, err)
			}
			gr.module = e.To
		} else {
			gr.module = f.Module.Mod.Path
		}
	}

	// requires: carry EVERY line (indirects too — they hold base's deliberate
	// version floors, e.g. a go-get -u'd security fix; regenerating them from
	// scratch could only reach the graph minimum). Importmap keys get mapped
	// path+version; everything else is carried verbatim. Tidy then validates:
	// prunes dead entries, raises below-minimum ones — never lowers a floor.
	var reqs []*modfile.Require
	for _, r := range f.Require {
		if e, ok := im[r.Mod.Path]; ok {
			consumed = true
			ver := rootVersion
			if ver == "" {
				die(1, "conf: root \"version\" is required — %s requires mapped module %s\n", srcPath, r.Mod.Path)
			}
			if ver == "@latest" {
				if dry {
					gr.unresolved = true
					gr.pins = append(gr.pins, fmt.Sprintf("%s @latest (unresolved)", e.To))
				} else {
					rv, rerr := resolveLatest(e.To)
					if rerr != nil {
						die(4, "resolve %s@latest: %v\n", e.To, rerr)
					}
					ver = rv
					gr.pins = append(gr.pins, fmt.Sprintf("%s %s", e.To, rv))
				}
			} else {
				gr.pins = append(gr.pins, fmt.Sprintf("%s %s", e.To, ver))
			}
			reqs = append(reqs, &modfile.Require{Mod: module.Version{Path: e.To, Version: ver}, Indirect: r.Indirect})
		} else {
			reqs = append(reqs, &modfile.Require{Mod: r.Mod, Indirect: r.Indirect})
		}
	}
	// SetRequireSeparateIndirect (not SetRequire): builds proper syntax lines AND
	// writes the canonical tidy-style layout — paren block for multiple directs,
	// bare line for one. Calling it later over bare SetRequire entries panics
	// (nil Syntax) — the API wants one canonical setter.
	f.SetRequireSeparateIndirect(reqs)

	// replaces: drop those targeting a mapped module (key or "to"); keep others
	toSet := map[string]bool{}
	for _, e := range im {
		toSet[e.To] = true
	}
	for _, rp := range append([]*modfile.Replace(nil), f.Replace...) {
		if _, isKey := im[rp.Old.Path]; isKey || toSet[rp.Old.Path] {
			if err := f.DropReplace(rp.Old.Path, rp.Old.Version); err != nil {
				die(4, "drop replace %s: %v\n", rp.Old.Path, err)
			}
			gr.dropReplace++
		}
	}
	// then emit importmap replaces
	for _, k := range sortedKeys(im) {
		e := im[k]
		if e.Replace != "" {
			if err := f.AddReplace(e.To, "", e.Replace, ""); err != nil {
				die(4, "add replace %s: %v\n", e.To, err)
			}
			gr.addReplace++
		}
	}

	// final touch-up before serialization: sort entries within blocks, drop
	// empty syntax. (Require layout is already canonical from the setter; the
	// indirect block is tidy's to append after the file is written.)
	f.SortBlocks()
	f.Cleanup()
	if !(dry && gr.unresolved) {
		out, ferr := f.Format()
		if ferr != nil {
			die(4, "format go.mod: %v\n", ferr)
		}
		gr.content = out
	}
	sort.Strings(gr.pins)
	return gr, consumed
}

func sortedKeys(im map[string]importEntry) []string {
	keys := make([]string, 0, len(im))
	for k := range im {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

// resolveLatest resolves <mod>@latest to a concrete version, inheriting the env.
func resolveLatest(mod string) (string, error) {
	dir, err := os.MkdirTemp("", "clone-srctree-latest-")
	if err != nil {
		return "", err
	}
	defer os.RemoveAll(dir)
	if err := os.WriteFile(filepath.Join(dir, "go.mod"), []byte("module clone.srctree.tmp\n\ngo 1.21\n"), 0o644); err != nil {
		return "", err
	}
	cmd := exec.Command("go", "list", "-m", "-f", "{{.Version}}", mod+"@latest")
	cmd.Dir = dir
	out, err := cmd.Output()
	if err != nil {
		return "", fmt.Errorf("go list -m %s@latest: %v", mod, err)
	}
	v := strings.TrimSpace(string(out))
	if v == "" {
		return "", fmt.Errorf("empty version for %s@latest", mod)
	}
	return v, nil
}

func tidyModule(dir string) {
	cmd := exec.Command("go", "mod", "tidy")
	cmd.Dir = dir
	// insulation: tidy is module-scoped by spec, but pin it explicitly so no
	// ambient go.work can ever influence what the generated go.mod resolves.
	cmd.Env = append(os.Environ(), "GOWORK=off")
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	if err := cmd.Run(); err != nil {
		die(3, "go mod tidy failed in %s: %v\n", dir, err)
	}
}
